#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="/data00/users/wanglikun/ProjWormLK/Vision-OPD"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-Vision-OPD-Qwen3.5-4B-released-b96-r8-gradaccum-sp4-rollout-tp1-retry}"

cd "${PROJECT_ROOT}"
EXPERIMENT_NAME="${EXPERIMENT_NAME}" \
ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE=1 \
ROLLOUT_GPU_MEMORY_UTILIZATION="${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.30}" \
ROLLOUT_MAX_NUM_SEQS="${ROLLOUT_MAX_NUM_SEQS:-16}" \
ACTOR_ULYSSES_SEQUENCE_PARALLEL_SIZE=4 \
TRAIN_BATCH_SIZE=96 \
PPO_MIMI_BATCH_SIZE=96 \
ROLLOUT_N=8 \
TRAINER_TOTAL_EPOCHS=1 \
TRAINER_SAVE_FREQ=1 \
  bash scripts/run_vision_opd_released_b96_r8_gradaccum_4b.sh "$@"
